#+OPTIONS: ^:nil

* Plauna

Plauna is a privacy focused service that helps you categorize your e-mails. All of its data is stored only on your computer.

You can parse your e-mails from mbox files or directly by connecting to your IMAP servers. Plauna helps you categorize your e-mails and automates the process so that incoming e-mails are moved to their respective folders on your IMAP server.

*IMPORTANT:* Plauna is still under heavy development at the moment. The features and the DB structure are subject to change.

* Installation

The easiest way to get Plauna is using the [[https://hub.docker.com/repository/docker/ozangulle/plauna/general][Docker image]].

The second way to get Plauna is fetching it from the git repository and compiling using Clojure CLI with the command:

#+BEGIN_SRC
clj -T:build uber
#+END_SRC

This will produce a Plauna uberjar in the ./target directory which you can run using a Java Runtime Environment.

* How to use

** How to run

You must provide a configuration file to start Plauna. By default, the configuration is expected to be at ~/.config/plauna.edn. You can modify the location of the configuration file by passing the parameter --config-file. This method is useful when running Plauna from the command line, e.g., java -jar plauna.jar --config-file=/opt/plauna/plauna.edn.

If you are using Docker, you can put the parameters in the environment variable PLAUNA_ARGS. A docker-compose example would look like this:

#+BEGIN_SRC docker-compose
services:
  plauna:
    container_name: plauna
    image: ozangulle/plauna:dev
    environment:
      - 'PLAUNA_ARGS=--config-file=/opt/plauna/plauna.edn'
    restart: unless-stopped
#+END_SRC

** Configuration

The following is a configuration file with all of the possible settings. The default value for data-folder is "~/.local/state/plauna" and the default value for the server port is 8080. The e-mail configurations have no default settings. Plauna can be run without any e-mail credentials, even though the key point of Plauna is having it automatically categorize your e-mails.

#+BEGIN_SRC clojure
    {:data-folder "/home/myhome/example-directory" ; the location for the db, training files and models
     :server {:port 80}
     :email {
             :clients [{:host "imap.example.com" :user "me@example.com" :secret "mysecret" :folder "Inbox"}]
    }}
#+END_SRC

** Getting Started

When you start Plauna, it starts a web server on the port which you specified (defaults to 8080) and connects to the IMAP servers that you configured. You can use Plauna without configuring any IMAP servers but you would be missing out on the "move e-mail" functionality. On your very first start, the database is empty. You need to fill it with e-mails. There are three non-exclusive ways of doing this:

1. Go to "Admin". Under the header "Parse E-mails" select an mbox file and click on the button "Parse Mbox". You can see your e-mails under the "E-mails" tab shortly thereafter.

2. Go to "Watchers", click on any IMAP account name, select a folder you want to parse the e-mails in, make sure "Move e-mails after categorization" is unchecked and click on the button "Parse E-mails". This will read all the e-mails in the selected folder.

3. Just leave Plauna running and watch it save your e-mails. Beware: Depending on how many e-mails you receive on any given day, this method may be very slow.

   
** Language Detection

Plauna automatically detects the language of an e-mail upon parsing it. Here, you must also select the languages that you want to use in training - therefore the languages you want to use in categorization.

** Categorization

*** Create Categories

Go to "Admin" -> "Manage Categories" in order to create and delete categories. If you set up connections to your IMAP servers in your settings file, anytime you create a category Plauna will try to create a folder on the servers. If you however delete a category, Plauna will not delete it on the server. As a general rule, Plauna reads and moves e-mails as well as it creates folders but it never deletes anything.

*** Categorize E-mails

Under the tab "E-mails" you can edit the language and category of every e-mail; either as a batch operation or by clicking on an e-mail and changing it at the details page.

*** Data Training

Under the tab "E-mails" there is an expandable section called "Data Training". Click on the button "Train with Existing Data" to train the model(s) using the existing categorized data. *Important:* You must have more than one category saved for each language you want to train in.

You must have selected at least one language in "Admin" -> "Manage Languages" in order to start training on your e-mails.

*** Automatic Categorization

After training your models on the categories you created, Plauna will categorize each e-mail you receive and moved it automatically to its corresponding folder.
